const registerRouter = require('./register')
const profileRouter = require('./profile')
const loginRouter = require('./login')
const eventsRouter = require('./events')
const resourcesRouter = require('./resources')
const adminRouter = require('./admin')
const shoppingRouter = require('./shopping')
const cartRouter = require('./cart')
const forgetRouter = require('./forget')

module.exports = app => {
    app.use('/register', registerRouter)
    app.use('/profile', profileRouter)
    app.use('/login', loginRouter)
    app.use('/events', eventsRouter)
    app.use('/resources', resourcesRouter)
    app.use('/admin', adminRouter)
    app.use('/shopping',shoppingRouter)
    app.use('/cart',cartRouter)
    app.use('/forget', forgetRouter)
}
